
dagRepo: https://github.com/elelement/airflow-gke.git
domain: airflow.example.com

web:
  name: web
  commandArgs: ["webserver"]

scheduler:
  name: scheduler
  commandArgs: ["scheduler"]

workers:
  name: worker
  replicas: 2
  commandArgs: ["worker"]

flower:
  name: flower
  commandArgs: ["flower"]
